-- ============================================
-- AgroVault Market Analysis Tables
-- Run this in Supabase SQL Editor after the
-- main schema has been created.
-- ============================================

-- ── 8. Market Analysis Snapshots ──
-- Stores periodic analysis results for each commodity.
-- Generated by the market-engine cron job every 4 hours.
CREATE TABLE IF NOT EXISTS agro_market_analysis (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "commodityId"   UUID           NOT NULL REFERENCES agro_commodities(id) ON DELETE CASCADE,
  "analysisType"  VARCHAR(50)    NOT NULL DEFAULT 'full',
  result          JSONB          NOT NULL,
  "generatedAt"   TIMESTAMP      NOT NULL DEFAULT now(),
  "createdAt"     TIMESTAMP      NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_market_analysis_commodity_time
  ON agro_market_analysis ("commodityId", "generatedAt" DESC);

-- ── 9. Price Forecasts ──
-- Stores daily price forecast snapshots.
CREATE TABLE IF NOT EXISTS agro_price_forecasts (
  id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "commodityId"     UUID           NOT NULL REFERENCES agro_commodities(id) ON DELETE CASCADE,
  "forecastDate"    DATE           NOT NULL,
  "predictedPrice"  DECIMAL(12,2)  NOT NULL,
  "confidenceLower" DECIMAL(12,2),
  "confidenceUpper" DECIMAL(12,2),
  "method"          VARCHAR(50)    NOT NULL DEFAULT 'blended_regression_wma',
  "reliability"     VARCHAR(20),
  "generatedAt"     TIMESTAMP      NOT NULL DEFAULT now(),
  "createdAt"       TIMESTAMP      NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_price_forecasts_commodity_date
  ON agro_price_forecasts ("commodityId", "forecastDate");

-- ── 10. Sell/Hold Recommendations Log ──
-- Stores generated recommendations for audit & analytics.
CREATE TABLE IF NOT EXISTS agro_recommendations (
  id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "userId"          UUID           NOT NULL REFERENCES agro_users(id) ON DELETE CASCADE,
  "storageUnitId"   UUID           REFERENCES agro_storage_units(id) ON DELETE SET NULL,
  "commodityId"     UUID           NOT NULL REFERENCES agro_commodities(id) ON DELETE CASCADE,
  recommendation    VARCHAR(20)    NOT NULL,
  urgency           VARCHAR(20)    NOT NULL,
  confidence        VARCHAR(20),
  "compositeScore"  DECIMAL(6,2),
  summary           TEXT,
  "fullResult"      JSONB,
  "generatedAt"     TIMESTAMP      NOT NULL DEFAULT now(),
  "createdAt"       TIMESTAMP      NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_recommendations_user
  ON agro_recommendations ("userId", "createdAt" DESC);

-- ============================================
-- RLS POLICIES
-- ============================================

-- Market analysis snapshots: public read
ALTER TABLE agro_market_analysis ENABLE ROW LEVEL SECURITY;

CREATE POLICY "market_analysis_select_all"
  ON agro_market_analysis FOR SELECT
  TO anon, authenticated
  USING ( true );

-- Price forecasts: public read
ALTER TABLE agro_price_forecasts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "price_forecasts_select_all"
  ON agro_price_forecasts FOR SELECT
  TO anon, authenticated
  USING ( true );

-- Recommendations: user can see their own
ALTER TABLE agro_recommendations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "recommendations_select_own"
  ON agro_recommendations FOR SELECT
  TO authenticated
  USING ( "userId" = auth.uid() );

-- ============================================
-- GRANTS
-- ============================================
GRANT SELECT          ON agro_market_analysis  TO anon, authenticated;
GRANT SELECT          ON agro_price_forecasts  TO anon, authenticated;
GRANT SELECT          ON agro_recommendations  TO anon, authenticated;
